# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jetsonano-smartgaitlab/Desktop/Projet/Projet_ETIS_SMARTGAIT_DATA_LOGGER

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jetsonano-smartgaitlab/Desktop/Projet/Projet_ETIS_SMARTGAIT_DATA_LOGGER

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jetsonano-smartgaitlab/Desktop/Projet/Projet_ETIS_SMARTGAIT_DATA_LOGGER/CMakeFiles /home/jetsonano-smartgaitlab/Desktop/Projet/Projet_ETIS_SMARTGAIT_DATA_LOGGER//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jetsonano-smartgaitlab/Desktop/Projet/Projet_ETIS_SMARTGAIT_DATA_LOGGER/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CAM_engine

# Build rule for target.
CAM_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CAM_engine
.PHONY : CAM_engine

# fast build rule for target.
CAM_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/build
.PHONY : CAM_engine/fast

#=============================================================================
# Target rules for targets named RADAR_engine

# Build rule for target.
RADAR_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RADAR_engine
.PHONY : RADAR_engine

# fast build rule for target.
RADAR_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/build
.PHONY : RADAR_engine/fast

Modules/CAMERA/CamAI.o: Modules/CAMERA/CamAI.cpp.o
.PHONY : Modules/CAMERA/CamAI.o

# target to build an object file
Modules/CAMERA/CamAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamAI.cpp.o
.PHONY : Modules/CAMERA/CamAI.cpp.o

Modules/CAMERA/CamAI.i: Modules/CAMERA/CamAI.cpp.i
.PHONY : Modules/CAMERA/CamAI.i

# target to preprocess a source file
Modules/CAMERA/CamAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamAI.cpp.i
.PHONY : Modules/CAMERA/CamAI.cpp.i

Modules/CAMERA/CamAI.s: Modules/CAMERA/CamAI.cpp.s
.PHONY : Modules/CAMERA/CamAI.s

# target to generate assembly for a file
Modules/CAMERA/CamAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamAI.cpp.s
.PHONY : Modules/CAMERA/CamAI.cpp.s

Modules/CAMERA/CamEngine.o: Modules/CAMERA/CamEngine.cpp.o
.PHONY : Modules/CAMERA/CamEngine.o

# target to build an object file
Modules/CAMERA/CamEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamEngine.cpp.o
.PHONY : Modules/CAMERA/CamEngine.cpp.o

Modules/CAMERA/CamEngine.i: Modules/CAMERA/CamEngine.cpp.i
.PHONY : Modules/CAMERA/CamEngine.i

# target to preprocess a source file
Modules/CAMERA/CamEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamEngine.cpp.i
.PHONY : Modules/CAMERA/CamEngine.cpp.i

Modules/CAMERA/CamEngine.s: Modules/CAMERA/CamEngine.cpp.s
.PHONY : Modules/CAMERA/CamEngine.s

# target to generate assembly for a file
Modules/CAMERA/CamEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamEngine.cpp.s
.PHONY : Modules/CAMERA/CamEngine.cpp.s

Modules/CAMERA/CamHardware.o: Modules/CAMERA/CamHardware.cpp.o
.PHONY : Modules/CAMERA/CamHardware.o

# target to build an object file
Modules/CAMERA/CamHardware.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamHardware.cpp.o
.PHONY : Modules/CAMERA/CamHardware.cpp.o

Modules/CAMERA/CamHardware.i: Modules/CAMERA/CamHardware.cpp.i
.PHONY : Modules/CAMERA/CamHardware.i

# target to preprocess a source file
Modules/CAMERA/CamHardware.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamHardware.cpp.i
.PHONY : Modules/CAMERA/CamHardware.cpp.i

Modules/CAMERA/CamHardware.s: Modules/CAMERA/CamHardware.cpp.s
.PHONY : Modules/CAMERA/CamHardware.s

# target to generate assembly for a file
Modules/CAMERA/CamHardware.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamHardware.cpp.s
.PHONY : Modules/CAMERA/CamHardware.cpp.s

Modules/CAMERA/CamStorage.o: Modules/CAMERA/CamStorage.cpp.o
.PHONY : Modules/CAMERA/CamStorage.o

# target to build an object file
Modules/CAMERA/CamStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamStorage.cpp.o
.PHONY : Modules/CAMERA/CamStorage.cpp.o

Modules/CAMERA/CamStorage.i: Modules/CAMERA/CamStorage.cpp.i
.PHONY : Modules/CAMERA/CamStorage.i

# target to preprocess a source file
Modules/CAMERA/CamStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamStorage.cpp.i
.PHONY : Modules/CAMERA/CamStorage.cpp.i

Modules/CAMERA/CamStorage.s: Modules/CAMERA/CamStorage.cpp.s
.PHONY : Modules/CAMERA/CamStorage.s

# target to generate assembly for a file
Modules/CAMERA/CamStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CAM_engine.dir/build.make CMakeFiles/CAM_engine.dir/Modules/CAMERA/CamStorage.cpp.s
.PHONY : Modules/CAMERA/CamStorage.cpp.s

Modules/RADAR/RadarEngine.o: Modules/RADAR/RadarEngine.cpp.o
.PHONY : Modules/RADAR/RadarEngine.o

# target to build an object file
Modules/RADAR/RadarEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarEngine.cpp.o
.PHONY : Modules/RADAR/RadarEngine.cpp.o

Modules/RADAR/RadarEngine.i: Modules/RADAR/RadarEngine.cpp.i
.PHONY : Modules/RADAR/RadarEngine.i

# target to preprocess a source file
Modules/RADAR/RadarEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarEngine.cpp.i
.PHONY : Modules/RADAR/RadarEngine.cpp.i

Modules/RADAR/RadarEngine.s: Modules/RADAR/RadarEngine.cpp.s
.PHONY : Modules/RADAR/RadarEngine.s

# target to generate assembly for a file
Modules/RADAR/RadarEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarEngine.cpp.s
.PHONY : Modules/RADAR/RadarEngine.cpp.s

Modules/RADAR/RadarHardware.o: Modules/RADAR/RadarHardware.cpp.o
.PHONY : Modules/RADAR/RadarHardware.o

# target to build an object file
Modules/RADAR/RadarHardware.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarHardware.cpp.o
.PHONY : Modules/RADAR/RadarHardware.cpp.o

Modules/RADAR/RadarHardware.i: Modules/RADAR/RadarHardware.cpp.i
.PHONY : Modules/RADAR/RadarHardware.i

# target to preprocess a source file
Modules/RADAR/RadarHardware.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarHardware.cpp.i
.PHONY : Modules/RADAR/RadarHardware.cpp.i

Modules/RADAR/RadarHardware.s: Modules/RADAR/RadarHardware.cpp.s
.PHONY : Modules/RADAR/RadarHardware.s

# target to generate assembly for a file
Modules/RADAR/RadarHardware.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarHardware.cpp.s
.PHONY : Modules/RADAR/RadarHardware.cpp.s

Modules/RADAR/RadarRealTime.o: Modules/RADAR/RadarRealTime.cpp.o
.PHONY : Modules/RADAR/RadarRealTime.o

# target to build an object file
Modules/RADAR/RadarRealTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarRealTime.cpp.o
.PHONY : Modules/RADAR/RadarRealTime.cpp.o

Modules/RADAR/RadarRealTime.i: Modules/RADAR/RadarRealTime.cpp.i
.PHONY : Modules/RADAR/RadarRealTime.i

# target to preprocess a source file
Modules/RADAR/RadarRealTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarRealTime.cpp.i
.PHONY : Modules/RADAR/RadarRealTime.cpp.i

Modules/RADAR/RadarRealTime.s: Modules/RADAR/RadarRealTime.cpp.s
.PHONY : Modules/RADAR/RadarRealTime.s

# target to generate assembly for a file
Modules/RADAR/RadarRealTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarRealTime.cpp.s
.PHONY : Modules/RADAR/RadarRealTime.cpp.s

Modules/RADAR/RadarStorage.o: Modules/RADAR/RadarStorage.cpp.o
.PHONY : Modules/RADAR/RadarStorage.o

# target to build an object file
Modules/RADAR/RadarStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarStorage.cpp.o
.PHONY : Modules/RADAR/RadarStorage.cpp.o

Modules/RADAR/RadarStorage.i: Modules/RADAR/RadarStorage.cpp.i
.PHONY : Modules/RADAR/RadarStorage.i

# target to preprocess a source file
Modules/RADAR/RadarStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarStorage.cpp.i
.PHONY : Modules/RADAR/RadarStorage.cpp.i

Modules/RADAR/RadarStorage.s: Modules/RADAR/RadarStorage.cpp.s
.PHONY : Modules/RADAR/RadarStorage.s

# target to generate assembly for a file
Modules/RADAR/RadarStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RADAR_engine.dir/build.make CMakeFiles/RADAR_engine.dir/Modules/RADAR/RadarStorage.cpp.s
.PHONY : Modules/RADAR/RadarStorage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CAM_engine"
	@echo "... RADAR_engine"
	@echo "... Modules/CAMERA/CamAI.o"
	@echo "... Modules/CAMERA/CamAI.i"
	@echo "... Modules/CAMERA/CamAI.s"
	@echo "... Modules/CAMERA/CamEngine.o"
	@echo "... Modules/CAMERA/CamEngine.i"
	@echo "... Modules/CAMERA/CamEngine.s"
	@echo "... Modules/CAMERA/CamHardware.o"
	@echo "... Modules/CAMERA/CamHardware.i"
	@echo "... Modules/CAMERA/CamHardware.s"
	@echo "... Modules/CAMERA/CamStorage.o"
	@echo "... Modules/CAMERA/CamStorage.i"
	@echo "... Modules/CAMERA/CamStorage.s"
	@echo "... Modules/RADAR/RadarEngine.o"
	@echo "... Modules/RADAR/RadarEngine.i"
	@echo "... Modules/RADAR/RadarEngine.s"
	@echo "... Modules/RADAR/RadarHardware.o"
	@echo "... Modules/RADAR/RadarHardware.i"
	@echo "... Modules/RADAR/RadarHardware.s"
	@echo "... Modules/RADAR/RadarRealTime.o"
	@echo "... Modules/RADAR/RadarRealTime.i"
	@echo "... Modules/RADAR/RadarRealTime.s"
	@echo "... Modules/RADAR/RadarStorage.o"
	@echo "... Modules/RADAR/RadarStorage.i"
	@echo "... Modules/RADAR/RadarStorage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

